### PR TITLE
Update social links

### PR DESCRIPTION
**Pull request by jdaudier**
Cleaned this up... LMK if it's ok

Support = chat (just like [6to5](https://6to5.org/))

new

**And... scroll down some more...**

new2

### CODE REVIEW

**Comment by jasonLaster** [comment]
Wow I love this. So much better thought through!

I want gitter to be front and center but I'm not sure about putting it in the nav. My expectation is that that links to somewhere on the site. Could we replace the GH Issues button with, "Say hi" or some gitter chat action oriented thing? I really like the other right links and wouldn't have a problem with GH issues over there. 

I just want to say how great this is again. I love how were discussing our openness. The community is everything.

**Comment by samccone** [comment]
@jdaudier looks like a rebase is in order

**Comment by jdaudier** [comment]
@samccone does this mean I don't have to do anything? or did you mean I need to rebase?

**Comment by samccone** [comment]
oh you need to rebase off of master

**Comment by jdaudier** [comment]
@samccone ok rebased

**Comment by jdaudier** [comment]
@samccone Did I get everything?

**Comment by jdaudier** [comment]
@sethkrasnianski By dependency section, do you mean bower.json file?

**Comment by paulfalgout** [comment]
@jdaudier I think @sethkrasnianski is talking about the section below the header..  I think however @jdaudier  just photoshopped two portions of the site together for review purposes.  The next section below the header is the about with the dependencies.

**Comment by jdaudier** [comment]
Oh right... it's 2 separates images... i added a line of words in between to reduce confusion

**Comment by jdaudier** [comment]
@samccone k, i think i got everything

**Comment by paulfalgout** [comment]
@samccone not super important, but why the leading `/` on this site?  It's certainly something we're not doing consistently, and for a static site like this I don't see much benefit. If anything it just forces me to have to run the python server from the `dist` directory  can't just `http://localhost:8000/dist/`  Not that I want to do that, but now that I know I can't, I _want_ to. :sunglasses:

**Comment by samccone** [comment]
brought in :)

**Comment by jasonLaster** [comment]
YESSSSSSS

**Pull request closed without merging**
