### PR TITLE
Sjk/social buttons

### PR DESCRIPTION
**Pull request by sethkrasnianski**
Gives the site a more branded look. Considering axing the gitter button as well but require a font icon / high res png.

screen shot 2015-01-04 at 11 00 45 pm

### CODE REVIEW

**Comment by jmeas** [comment]
Mmm...I think the more standard buttons look better.

**Comment by samccone** [comment]
I am a fan of this direction more, much more consistent and matches the rest of the site.

It also has the added advantage of cutting loadtime and weird CSS jump from the github and twitter iframes

:+1:

**Comment by jdaudier** [comment]
will the github stars number update automatically like before?

**Comment by sethkrasnianski** [comment]
It will. It's making an Api call to fetch the count.

**Comment by jdaudier** [comment]
cool @sethkrasnianski!  mind if I play around with your version and try different styles to see how it might look?  I feel that it competes w/ our main CTA button, so I was gonna try gray or some other ideas.

**Comment by jasonLaster** [comment]
Thanks @sethkrasnianski! I agree, taking control of these buttons is awesome for perf and aesthetics. Major style points. Keep it coming.

**Comment by samccone** [comment]
merging ... we can iterate more obviously

**Comment by sethkrasnianski** [comment]
@jdaudier go for it :+1:

**Pull request merged**
