### PR TITLE
Lazy load youtube vids then swipe out for videos when user clicks on play button

### PR DESCRIPTION
**Pull request by kkemple**
@samccone @trezy 
Okay, so instead of loading the videos on page load, we just pull in the standard definition screenshots of the videos from the youtube api. Then if a use clicks on the play button over the screenshot we build the iframe and swap it out for the screenshot. This way the user never has to download the video unless they plan to watch it. I attached a screenshot of this in action, and of the network speeds for the images. (Much :zap: :zap:)

network-times
video-preview
example-usage

> Note: The iframes are left in the jade temple so this is not technically ready for a merge just yet, if you like the idea and direction I will strip them out and we can get this in to master.

### CODE REVIEW

**Comment by samccone** [comment]
OMMMMMG YESSSSSSSSSS

**Comment by kkemple** [comment]
okay cool, i will remove the commented out iframes and it will be ready for merge

**Comment by kkemple** [comment]
and the http: for images

**Comment by samccone** [comment]
yep just squash this down into 1 commit with an interactive rebase

`git rebase -i origin/master`

**Comment by kkemple** [comment]
you got it

**Comment by kkemple** [comment]
okay good to go!! :+1:

**Comment by samccone** [comment]
:clap: amazing

**Comment by jdaudier** [comment]
@kkemple I'll have to ask you about what the JS is doing in person.  I know it's lazy loading but would love to have you walk me through it.

One suggestion, can we make the thumbnail the same size as the video once it starts playing so the text don't re-flow.  It only happens with these 2 vids... 
img

Thanks!

**Comment by kkemple** [comment]
Huh I didn't catch that, I will take a look, and lazy loading may not be the best term, essentially we are just creating the iframe when the user clicks on the screenshot which means we don't have to download the src for the iframe until the user wants it, instead of downloading it on page load, then we just remove the play button and image since we now have the iframe

**Comment by jdaudier** [comment]
@kkemple gotcha

**Comment by jdaudier** [comment]
i think the term is "play on demand"

**Pull request merged**
