### PR TITLE
Add doc files order

### PR DESCRIPTION
**Pull request by denar90**
PR due to task #447 

I've commited also changes to submodule, is it ok?

### CODE REVIEW

**Comment by jdaudier** [comment]
Ping @samccone @peterblazejewicz @paulfalgout 

I will check this out this weekend.

**Comment by peterblazejewicz** [comment]
I've looked into PR already. For me that is LGTM. If anything, folks committing to project source can discuss content significance (should `Functions` be more prominent than `Application` concept in docs, etc). Thanks!

**Comment by jdaudier** [comment]
@denar90 Merged! Thanks for your patience!

**Comment by denar90** [comment]
Awesome!

**Pull request merged**
