### PR TITLE
Resources not loaded via https

### PR DESCRIPTION
**Pull request by denar90**
Fixed for docs pages, related to #497

### CODE REVIEW

**Comment by samccone** [comment]
lgtm

**Comment by denar90** [comment]
Since travis has Security Restrictions https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions we were not able to use gh token for pr's, so I made it public.

**Comment by paulfalgout** [comment]
Can we safely make that token public?

**Comment by denar90** [comment]
It has not access preferences, so if someone uses it for fetching github data, he/she will use all limit and that's it I think...

**Comment by denar90** [comment]
@paulfalgout I removed running tests for PR... No public access though...

**Comment by peterblazejewicz** [comment]
@denar90 Thanks! It seems I overlooked some parts covered by your PR!

**Pull request merged**
