### PR TITLE
Sourcemaps .. because 2015

### PR DESCRIPTION
**Pull request by samccone**
Source maps are nice, and we are nice. Let's use them :)

nice nice

screen shot 2015-02-22 at 11 45 26 am

### CODE REVIEW

**Comment by jasonLaster** [comment]
Lol  okay

**Comment by samccone** [comment]
hahaha i mean it makes life easier to work on the site

**Comment by peterblazejewicz** [comment]
LGTM

**Comment by peterblazejewicz** [comment]
@samccone I'll post-fix comma rebasing #293

**Pull request merged**
