### PR TITLE
Update files order due to v3 docs

### PR DESCRIPTION
**Pull request by denar90**
Updated docs ordering due to https://github.com/marionettejs/backbone.marionette/issues/3066

screen shot 2016-08-21 at 15 26 25

### CODE REVIEW

**Comment by paulfalgout** [comment]
Is this just for pre4?  in v3 many of these files don't exist.  AbstractView.. RegionManager etc.

**Comment by denar90** [comment]
It's just sort list, if element is absent it will be ignored. So it works for all versions. Real code which doing sorting is https://github.com/marionettejs/marionettejs.com/blob/master/tasks/compile-docs.js#L164-L169

**Comment by scott-w** [comment]
:+1:

**Comment by ahumphreys87** [comment]
👍

**Pull request merged**
