### PR TITLE
Introduce page top level vars block

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit adds page top level block variables together
with required tooling and example usage to render page specific
changes and styles easily.
Amongst others:
- introduces locals.json data file to hold all globals (template specific) variables
- change data function in Jade task to return single, unified object built with the same api
- adds body class variable to introduce per-page theming
- adds required folder structure and examples page related Sass files

@jdaudier 
These changes should allow to better per-page modifications - instead of duplicating code we will be able to use some common style (e.g. for download-section) and fine tune it in per-page spefic file.

The structure is based on:
- Wintersmith `bodyclass` implementation:  
https://github.com/jnordberg/wintersmith/blob/master/examples/blog/templates/layout.jade#L16
https://github.com/jnordberg/wintersmith/blob/master/examples/blog/templates/article.jade#L5
- Sass guides for structuring content:  
http://sass-guidelin.es/#pages-folder

### CODE REVIEW

**Comment by samccone** [comment]
:+1: 

the only downside I see here is that if we combine all the CSS into one file for all pages we are going to be adding serious bloat to each page load. 

just a thought, what do you guys think?

**Comment by jasonLaster** [comment]
:+1: I think this is a great org scheme and bloats something we should measure down the road.

**Comment by peterblazejewicz** [comment]
> the only downside I see here is that if we combine all the CSS into one file for all pages we are going to be adding serious bloat to each page load.

That's not the intent - the sample pages related styles are to be included wisely (I'll update PR with change reflecting this)

**Comment by peterblazejewicz** [comment]
The PR's sample implementation is updated - now the main index style file is importing related page styles only. With changes like these the index.scss style for `inspector` page could be rewritten to:
```scss
@import "../reset";
@import "../variables";
@import "../vendor/mo";

@import "../pages/inspector";
```
where all page related styles are in `_inspector` partial

**Comment by samccone** [comment]
:+1:

**Pull request merged**
