### PR TITLE
Add JSHint and editors config files

### PR DESCRIPTION
**Pull request by peterblazejewicz**
To lint or not to lint. Files are based on Mj files.
JSHint config file is based on: http://git.io/AAP6
EditorConfig file is based on: http://git.io/AA62

### CODE REVIEW

**Comment by samccone** [comment]
If we are going to add these we will want to run an automated task that will cause tests to fail. We would also want to change the CI setup to make it so it would run CI on all branches and only run deploy on master

**Comment by peterblazejewicz** [comment]
But that is rather for our own scripts from "js" directory, for now I want to use them to stay consistent. I've built-in support for JSHint/EditorConfig - so just to let people write consistent code without enforcing failures yet.

**Comment by ahumphreys87** [comment]
I'm adding JSCS to marionette using the Grunt preset, should we add this at
the same as these 2?

**Comment by peterblazejewicz** [comment]
@ahumphreys87 I'm :+1:  I want to promote consistent writing style - without enforcing rules yet. We could just add grunt task to run linters - but not as part of build process.
cc/ @samccone  ?

**Comment by jasonLaster** [comment]
:tada:

**Comment by jdaudier** [comment]
:+1:

**Comment by samccone** [comment]
hmmm if we don't enforce them it is too easy to ignore, that is my concern, I can make the changes to travis to complain if it fails... thoughts?

**Comment by jdaudier** [comment]
yes, i think it should be enforced or else it's too easy to miss

**Comment by peterblazejewicz** [comment]
OK. Let me try to write this (grunt project file, our source code js files, our scss files, not jade unless someone knows Jade linter in with grunt task)

**Comment by peterblazejewicz** [comment]
@ahumphreys87 @samccone would you mind comment and review?
Do we need the same `lint` task that is run in Mj core library here?
https://github.com/marionettejs/backbone.marionette/blob/master/Gruntfile.js#L297

**Comment by ahumphreys87** [comment]
@peterblazejewicz looking good, yeah we will need that - I'd also add `lint` to the `scripts` watch task and maybe the compile-site task

**Comment by peterblazejewicz** [comment]
@ahumphreys87 thanks! let's see Sam's input

**Comment by peterblazejewicz** [comment]
updated/rebased

**Comment by jdaudier** [comment]
@peterblazejewicz I'm curious about lintspaces.  I thought spacing is handled by JSCS already. This is just for my own knowledge.

**Comment by peterblazejewicz** [comment]
@jdaudier yes, JSCS does apply rules related to white space, so `lintspaces` seems like superfluous here, but it can be used for other files too and also uses `.editorconfig` files. JSCS also does things with white space use in statements - which `lintspaces` does not - but I've taken used tools from Mt:
https://github.com/marionettejs/backbone.marionette
 so we are now using the common tools and config. We are free to use them differently in tasks though.

**Comment by samccone** [comment]
ah shucks can you rebase this sucker @peterblazejewicz 

thanks again

**Comment by peterblazejewicz** [comment]
updated/rebased/resolved - not yet squashed to see what is changing in steps

**Comment by peterblazejewicz** [comment]
updated via rebase after #357

**Comment by samccone** [comment]
moved to #379

**Pull request closed without merging**
