### PR TITLE
Add icons to Inspector page section headings

### PR DESCRIPTION
**Pull request by jdaudier**
#### OLD:
image

#### NEW:
image

### CODE REVIEW

**Comment by jdaudier** [comment]
@peterblazejewicz Should we change the h2 with an h4 class to an h2 class?

https://github.com/marionettejs/marionettejs.com/blob/master/src%2Finspector%2Findex.jade#L32

**Comment by peterblazejewicz** [comment]
@jdaudier
I've added `.h4` class alias to have `h4` like style applied to `h2` after markup change:
https://github.com/marionettejs/marionettejs.com/commit/d73f92373944c8ce7151f278b4500a00438955b6
We should remove that class alias:
https://github.com/marionettejs/marionettejs.com/pull/336#commitcomment-10039854
not necessairly `h4` declaration.
The semantic `h2` on this page should should have this style from `.h4` alias now.

**Comment by jasonLaster** [comment]
Wow! That's so good joanne!

**Comment by jasonLaster** [comment]
Side comment. I could see the try it out link bring its own section below. 

The advantage is we could add a better description like. Install the inspector and try it out on the marionette wires app.

**Comment by jdaudier** [comment]
@peterblazejewicz Is this what you mean? I don't know what magic you did but the h2 styles didn't affect the homepage h2 styles?

https://github.com/marionettejs/marionettejs.com/commit/91547015463962ae84ba3972c7891846c09e3dc0

**Comment by jdaudier** [comment]
@jasonLaster I like how it's evenly in 2 rows right now.  Let me think about how to lay that out nicely.

**Comment by peterblazejewicz** [comment]
@jdaudier 
There are no heading styles from other pages here - except of reset styles. So there is no problem to fix here as on landing/downloads pages.
When I wrote about dedicated heading classes I though about something like here:
https://github.com/twbs/bootstrap/blob/master/less/panels.less#L32-L46
The .panel has a title heading class - which is specifically written to override default heading styles (set by normalize>fonts styles).

**Comment by jdaudier** [comment]
@peterblazejewicz just realized that inspector page is using its own CSS and that's why it didn't affect the homepage.

**Comment by peterblazejewicz** [comment]
@jdaudier 
> And am I ok here? 9154701

Yes

**Pull request merged**
