### PR TITLE
Inline critical menu JS

### LINKED ISSUE #343: Mobile menu toggle seems to no longer be working.
On a phone if you click the menu button, it seems to no longer open :(

### PR DESCRIPTION
**Pull request by samccone**
This allows even on a slow network for the menu interaction to work
right away, as compared to when ALL of the JS has loaded.

Fixes #343

### CODE REVIEW

**Comment by jdaudier** [comment]
LGTM
:+1: for vanilla JS!

**Comment by peterblazejewicz** [comment]
```JavaScript
script.
  // Toggle top nav
  var navSlider = document.querySelector('.nav-slider');
  var toggleButton = document.querySelector('button.menu-icon');
  toggleButton && toggleButton.addEventListener('click', function() {
    navSlider && navSlider.classList.toggle('closed');
  });
```
- script text/javascript is default in html5
- querySelector is shorter, always return single element and results can be used directly in safety checks (via vars)
- `toggle` does the job (if we already dropped IE9 using `classList`)

We should later move that script into bottom scripts block using Jade `prepend` instead of embedding this into html template. When prepended it will do the same job.

We could also convert Google fonts to self hosted - to avoid that SPOF I've linked in issue.

**Comment by jdaudier** [comment]
@peterblazejewicz curious as to why you have to repeat `toggleButton` in `toggleButton && toggleButton.addEventListener` and same for `navSlider`?

**Comment by peterblazejewicz** [comment]
this is a JS shorcut.
I could write:
```JavaScript
if (toggleButton) {
  toggleButton.addEventListener(....)
}
```
or use shortcut using evaluation with && conjunction  (it fails quickly if first is null/false):
```JavaScript
toggleButton && toggleButton.AddEventListener(.....)
```
This is used in well established frameworks, say in Bootstrap:
https://github.com/twbs/bootstrap/blob/master/js/modal.js#L182
https://github.com/twbs/bootstrap/blob/master/js/modal.js#L224
https://github.com/twbs/bootstrap/blob/master/js/tooltip.js#L101-L103
If such shortcuts are used depends on project, we could have JS code style that prohibits them promoting use of explicit `if` blocks.

**Comment by samccone** [comment]
bah good call @peterblazejewicz updating

**Comment by samccone** [comment]
kk @peterblazejewicz let me know, I ended up using a polyfill, so that we don't drop support. I have also included the file inline with the nav component so that there is no additional network request.

**Comment by peterblazejewicz** [comment]
LGTM
Later we should minimize JS code after concatenation - including this inline scripts.

**Comment by samccone** [comment]
I agree :)

**Comment by peterblazejewicz** [comment]
@samccone 
- minify inlined polyfill (always, including production)
- minify build.js in production only:
```diff
commit fcd88d0805dddaeaf7fef657c441a8ada7fc2333
Author: Peter Blazejewicz <peter.blazejewicz@gmail.com>
Date:   Sun Mar 8 22:35:51 2015 +0100

    Minify JavaScript source code
    - add Grunt UglifyJS task dependency
    - minify inlined JavaScript in development and production
    - minify main source code in production only

diff --git a/gruntfile.js b/gruntfile.js
index a9a5d08..3253688 100644
--- a/gruntfile.js
+++ b/gruntfile.js
@@ -74,6 +74,26 @@ module.exports = function(grunt) {
       }
     },
 
+    uglify: {
+      options: {
+        compress: true,
+        mangle: false,
+        preserveComments: false,
+        screwIE8: true,
+        sourceMap: false
+      },
+      dist: {
+        files: {
+          'dist/js/build.js': ['<%= concat.dist.dest %>']
+        }
+      },
+      polyfills: {
+        files: {
+          'dist/js/classList.js': ['bower_components/html5-polyfills/classList.js']
+        }
+      }
+    },
+
     docco: {
       build: {
         src: ['backbone.marionette/lib/backbone.marionette.js'],
@@ -221,7 +241,7 @@ module.exports = function(grunt) {
       },
       scripts: {
         files: 'src/js/**/*',
-        tasks: ['notify:preHTML', 'concat', 'copy', 'notify:postHTML']
+        tasks: ['notify:preHTML', 'concat', 'uglify:polyfills', 'copy', 'notify:postHTML']
       },
       assets: {
         files: 'src/images/**/*',
@@ -331,6 +351,7 @@ module.exports = function(grunt) {
     'svgstore',
     'sass:dist',
     'concat',
+    'uglify',
     'copy',
     'imagemin',
     'compile-templates',
diff --git a/package.json b/package.json
index fcf06ad..3604b9e 100644
--- a/package.json
+++ b/package.json
@@ -41,6 +41,7 @@
     "grunt-contrib-copy": "0.5.0",
     "grunt-contrib-imagemin": "0.9.2",
     "grunt-contrib-jade": "0.12.0",
+    "grunt-contrib-uglify": "^0.8.0",
     "grunt-contrib-watch": "0.6.1",
     "grunt-critical": "^0.1.2",
     "grunt-docco": "0.3.3",
diff --git a/src/sections/_nav.jade b/src/sections/_nav.jade
index 815a3da..02e00cc 100644
--- a/src/sections/_nav.jade
+++ b/src/sections/_nav.jade
@@ -30,7 +30,7 @@ header.global-nav
 
 // Inline menu behavior since we want it to work right away regardless of network speed
 script
-  include ../../bower_components/html5-polyfills/classList.js
+  include ../../dist/js/classList.js
 
 script.
   var menu = document.getElementsByClassName('menu-icon')[0],
```
Thoughts?

**Comment by samccone** [comment]
oh yeah good call :+1:

**Comment by peterblazejewicz** [comment]
KK, will PR tomorrow. Thanks!

**Comment by jdaudier** [comment]
@peterblazejewicz interesting JS shortcut... i didn't know you don't even need the `if`

**Pull request merged**
