### PR TITLE
Fix YouTube button regression - closes #283

### LINKED ISSUE #283: Video button regression
screen shot 2015-02-20 at 6 18 58 pm

### PR DESCRIPTION
**Pull request by jdaudier**
Doesn't look transparent locally....

### CODE REVIEW

**Comment by samccone** [comment]
:+1:

**Comment by jdaudier** [comment]
If it's still transparent on production, then something odd is happening.  I opened up the SVG in Illustrator and the triangle is definitely filled w/ white color.

**Comment by peterblazejewicz** [comment]
That's SVG optimize/Image optimize task that is run only on compile-site task. Let's investigate this.

**Comment by peterblazejewicz** [comment]
@jdaudier you could close this without merge - we have already found the problem source:
https://github.com/addyosmani/critical/issues/63

**Comment by jdaudier** [comment]
i would've never guessed it was that

**Pull request closed without merging**
