### PR TITLE
Add Marionette.Inspector page

### PR DESCRIPTION
**Pull request by samccone**
Thanks to @lupinskij for the design and @jasonLaster for the copy (from the inspector repo)

Let me know if anything is wrong of if this is a good pass.

screen shot 2015-02-15 at 6 02 24 pm

### CODE REVIEW

**Comment by jdaudier** [comment]
design looks good!

**Comment by samccone** [comment]
anyone want to read over the copy and let me know?

**Comment by ahumphreys87** [comment]
Copy reads well to me. But then again I'm British so may not want to take my word for it :p

**Comment by peterblazejewicz** [comment]
I still think that every a beast like software tool should have its own namespace - here it should have its own Twitter @ and hashtag defined early - so we can reference it in communication - even if people do not use Twitter icons directly: #241

**Pull request merged**
