### PR TITLE
Added "updates" button to check new releases

### PR DESCRIPTION
**Pull request by Woile**
Shows the changelog.

### CODE REVIEW

**Comment by jdaudier** [comment]
ping @peterblazejewicz 

I will take a look this weekend.  Sorry for the delay @Woile.

**Comment by jdaudier** [comment]
@Woile Do you mind looking into why the font types & sizing varies?  I think you meant to have them be the same.

font

font2

**Comment by Woile** [comment]
@jdaudier I fixed the styles. It should be noted though, that the changelog does not keep the same format through the entire file. Eg:
Sometimes to list items is used this:
```
#### Docs

* Improve document
```
And sometimes this is used:
```
* Bug Fixes

  * LayoutView’s regions 
```

If you want I can take the time to make a pull request fixing the issue in the changelog.md. You can tell me the format we should use or I can choose it for you, it's the same for me.

**Comment by jdaudier** [comment]
@Woile Will check this out this weekend.  Sorry for the delay.

**Comment by jdaudier** [comment]
@trezy @samccone @peterblazejewicz: Can we merge this in? Thumbs?

@Woile :+1: 

I noticed some spacing differences but it's prob due to the way the changelog was created.

match

**Comment by trezy** [comment]
:+1:

**Comment by jdaudier** [comment]
Should I ignore the CI errors and merge, or will that cause the site to go down in flames?  @samccone @trezy

**Comment by samccone** [comment]
I am looking into the CI stuff right now actually.. give me a few hours ;)

**Comment by jdaudier** [comment]
thanks @samccone! (I also update my other [PR](https://github.com/marionettejs/marionettejs.com/pull/434) since I noticed it contained an extra commit that I didn't meant to add)

**Comment by samccone** [comment]
@Woile mind a rebase off of master?

**Comment by Woile** [comment]
@samccone Done.

**Comment by samccone** [comment]
oh i know what this error code is from.. 1 min fixing

**Comment by samccone** [comment]
@Woile ok once more :)

**Comment by Woile** [comment]
@samccone done.

**Comment by peterblazejewicz** [comment]
:+1:  (and remember to update Bower deps before publishing)

There is a small problem to be fixed under small screens, as the page is using `<code>` tags.
Other page navbar menu expanded:

Updates page menu expanded:


The `<code>` tag responsible (in this specific case) for overflow selected on the right.

**Comment by jdaudier** [comment]
@Woile Might fixing the mobile bug per @peterblazejewicz's suggestion?

**Comment by Woile** [comment]
@jdaudier @samccone I've added a media query to solve the problem reported by @peterblazejewicz. I think it's fixed, but my css skills are not the best, so if it's not working please someone take a look, I would be really glad.
Thanks!

**Comment by jdaudier** [comment]
@samccone @peterblazejewicz @paulfalgout Are we ok to merge this in?

**Comment by peterblazejewicz** [comment]
@jdaudier 
I could be wrong, but the PR should be tested againts latest changes from master. There are no problems with Git itself, there were be clean merge. But I've got visual problems when testing against current master:
image

How I tested using local synced fork:
- 1) either updating and rebasing PR branch:  `cd pr/431`, `git fetch marionettejs`, `git rebase marionettejs/master` (clean rebase)
or:
- 2) or updating local master and merging PR branch:  `cd master`, `git fetch marionnettejs`, `git merge marionettejs/master` (clean merge) and then `git merge pr/431`

I could miss something, but I've just got this visual problem.

**Comment by jdaudier** [comment]
ok let me merge it in and see on my local

**Comment by Woile** [comment]
@jdaudier could u merge it? Does anything need to be fixed?

**Comment by jdaudier** [comment]
@Woile Can you pull in the latest master and see how your code looks with it?  I was going to check it later tonight.

**Comment by Woile** [comment]
@jdaudier I'll try it later, after work.

**Comment by Woile** [comment]
@jdaudier now it should be working

**Comment by peterblazejewicz** [comment]
@jdaudier 
corrected

**Comment by jdaudier** [comment]
@Woile :+1:  Can you please squash into 1 commit and we should be good to merge?  Thanks for all the help!

@peterblazejewicz @paulfalgout @samccone Another thumb please?

**Comment by peterblazejewicz** [comment]
@jdaudier I've already checked: https://github.com/marionettejs/marionettejs.com/pull/431#issuecomment-175245086
:+1:

**Comment by jdaudier** [comment]
@Woile :+1:  Can you please squash into 1 commit and we should be good to merge?  Thanks for all the help!

**Comment by Woile** [comment]
@jdaudier I already did the squash on commit `5305e25`, I dunno how to do it better haha, sorry :/

**Comment by jdaudier** [comment]
@Woile I think the commits will just show up as 1 here: https://github.com/marionettejs/marionettejs.com/pull/431/commits

You will need to force push to your local branch.

@samccone Correct me if I'm wrong. Tks!

**Comment by jdaudier** [comment]
@woile Thanks for the great work! We finally squashed and merged it in via @ianmstew's #437 PR.

**Comment by ianmstew** [comment]
:+1:  :smile:

**Comment by Woile** [comment]
thank you @jdaudier and everyone else, I've been really busy at work and college.

**Pull request closed without merging**
