### PR TITLE
Add top nav

### PR DESCRIPTION
**Pull request by jdaudier**
Woot! 

I tried to make it responsive but I'm not super good at it... in case anyone wants to make it better.

marionette

### CODE REVIEW

**Comment by samccone** [comment]
yep this is an improvement :clap: thanks @jdaudier

**Comment by jdaudier** [comment]
* hide download button on mobile
* remove small gap on right side on mobile
* twitter button only shows text on android 4.4

**Comment by jdaudier** [comment]
* remove small gap on right side on mobile (see screenshot)
* twitter button only shows text on android 4.4 (see screenshot)

screenshot_2015-01-04-12-47-39

**Comment by jasonLaster** [comment]
Ooh pretty

**Comment by jdaudier** [comment]
* twitter button only shows text on android 4.4 (see screenshot) -- but this is ok with me as text I think

screenshot_2015-01-04-12-47-39

**Pull request merged**
