### PR TITLE
Add Veeqo logo to the companies section

### PR DESCRIPTION
**Pull request by vasiliy-pdk**
I believe each logo of a company using Marionette helps to increase Marionette`s popularity because newcomers will be more confident about their choice.

### CODE REVIEW

**Comment by vasiliy-pdk** [comment]
I have no idea why this test failed on CI: 

```
1 test failed
  1. Get youtube data
  AssertionError: [] === [ { title: 'Backbone.js with Derick Bailey - April 2013',
    img: 'htt
        _callee3$ (addditonal-resources.js:34:5)
        tryCatch (/home/travis/build/marionettejs/marionettejs.com/node_modules/regenerator-runtime/runtime.js:64:40)
        GeneratorFunctionPrototype.invoke [as _invoke] (/home/travis/build/marionettejs/marionettejs.com/node_modules/regenerator-runtime/runtime.js:355:22)
```

**Comment by peterblazejewicz** [comment]
@vasiliy-pdk I've restarted the build (sometimes Travis just fails). Have you run `npm test` locally?

**Comment by vasiliy-pdk** [comment]
> Have you run npm test locally?

Unfortunately, all the tries to deploy the site for local development failed. I tried to use the same node, npm, nvm versions I saw in Travis CI log and tried to use the freshest ones.

The last try:

```
vasyl@insp7548:~/Code/marionettejs.com$ node --version
v5.3.0
vasyl@insp7548:~/Code/marionettejs.com$ npm --version
3.3.12
vasyl@insp7548:~/Code/marionettejs.com$ nvm --version
0.33.0
vasyl@insp7548:~/Code/marionettejs.com$ npm cache clean
vasyl@insp7548:~/Code/marionettejs.com$ npm install
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated jade@1.3.1: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! tar.unpack unzip error /tmp/npm-26077-e490a5fc/registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000382.tgz
npm ERR! tar.unpack untar error /tmp/npm-26077-e490a5fc/registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000382.tgz
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/home/vasyl/.nvm/versions/node/v5.3.0/bin/node" "/home/vasyl/.nvm/versions/node/v5.3.0/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vasyl/Code/marionettejs.com/npm-debug.log
vasyl@insp7548:~/Code/marionettejs.com$ npm run setup

> marionettejs.com@0.0.0 setup /home/vasyl/Code/marionettejs.com
> ./setup.sh

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated jade@1.3.1: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! tar.unpack unzip error /tmp/npm-27057-06a7d03f/registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000382.tgz
npm ERR! tar.unpack untar error /tmp/npm-27057-06a7d03f/registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000382.tgz
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/home/vasyl/.nvm/versions/node/v5.3.0/bin/node" "/home/vasyl/.nvm/versions/node/v5.3.0/bin/npm" "i"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vasyl/Code/marionettejs.com/npm-debug.log

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/home/vasyl/.nvm/versions/node/v5.3.0/bin/node" "/home/vasyl/.nvm/versions/node/v5.3.0/bin/npm" "run" "setup"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! marionettejs.com@0.0.0 setup: `./setup.sh`
npm ERR! Exit status 251
npm ERR! 
npm ERR! Failed at the marionettejs.com@0.0.0 setup script './setup.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the marionettejs.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./setup.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls marionettejs.com
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vasyl/Code/marionettejs.com/npm-debug.log

```

**Comment by peterblazejewicz** [comment]
These last ones could be due to Node version, see my comment: https://github.com/marionettejs/marionettejs.com/pull/493#discussion_r99477193

**Comment by vasiliy-pdk** [comment]
After deleting `npm-shrinkwrap` the system has been deployed locally. Different test failed during testing. 

```
vasyl@insp7548:~/Code/marionettejs.com$ npm run test

> marionettejs.com@0.0.0 test /home/vasyl/Code/marionettejs.com
> ava

loudRejection/api is deprecated. Use the currently-unhandled module instead.

   4 passed
   1 failed

  1. Get youtube data
    
  t.deepEqual(videoData, dataMochs.videoData)
        ?                                    
        ?                                    
        SyntaxError: Unexpected token (1:6)  
                                             
  If you are using `babel-plugin-espower` and want to use experimental syntax in your assert(), you should set `embedAst` option to true.
  see: https://github.com/power-assert-js/babel-plugin-espower#optionsembedast
                                             
                                             
  
      img: 'htt
        _callee3$ (addditonal-resources.js:34:5)
        tryCatch (/home/vasyl/Code/marionettejs.com/node_modules/regenerator-runtime/runtime.js:64:40)
        GeneratorFunctionPrototype.invoke [as _invoke] (/home/vasyl/Code/marionettejs.com/node_modules/regenerator-runtime/runtime.js:355:22)
        GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/vasyl/Code/marionettejs.com/node_modules/regenerator-runtime/runtime.js:116:21)

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/home/vasyl/.nvm/versions/node/v5.3.0/bin/node" "/home/vasyl/.nvm/versions/node/v5.3.0/bin/npm" "run" "test"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! marionettejs.com@0.0.0 test: `ava`
npm ERR! Exit status 1

```

**Comment by vasiliy-pdk** [comment]
Anyway, I don't think that adding the logo may cause those tests to fail :)

**Comment by denar90** [comment]
@peterblazejewicz I think it fails because of youtube API key. I had the same issue locally and developing #493 
I generated new one so it should work well.
@vasiliy-pdk can you attach screenshot with if it works locally? So we can merge it.

**Comment by vasiliy-pdk** [comment]
@denar90, do you mean screenshot of the page with companies? 

screenshot from 2017-02-05 22 06 21
screenshot from 2017-02-05 22 05 39

**Comment by JSteunou** [comment]
:+1:

**Comment by denar90** [comment]
👍 
but lets merge it after #493

**Comment by vasiliy-pdk** [comment]
Thank you, guys! :+1:

**Pull request merged**
