### PR TITLE
Remove titles from generated SVG sprites

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit fixes obscure problem where text titles from SVG sprites
are visible for screen readers, crawlers and other non-visual readers.
We are already using screen-reader textual context for SVG icons, so
there is no reason why we should use this default SVGStore option.
Setting default title property inclusion to false removes that obscure
problems from generated content.
For details please see images attached to PR - the screenshots of readers
supporting nice, readable text is most important.

before:

after:

before:

after:

Thanks!

### CODE REVIEW

**Comment by samccone** [comment]
wow crazy but I guess it makes sense

**Comment by jdaudier** [comment]
@peterblazejewicz Maybe you told me before but can you tell me the tools you're using for this PR, specifically for the screenreader stuff? This is just for my own knowledge.  Thanks!

BTW, I think you should write a blog post about your process so we can post it on the Mn blog to share w/ the community.

**Comment by peterblazejewicz** [comment]
@jdaudier (lynx and FireFox in above screenshots)
- lynx  
http://en.wikipedia.org/wiki/Lynx_(web_browser)
http://en.wikipedia.org/wiki/Lynx_(web_browser)#Accessibility
http://en.wikipedia.org/wiki/Lynx_(web_browser)#Web_design_and_robots
https://support.google.com/webmasters/answer/40349?hl=en
- built-in browser readers:  
(Safari)  
https://support.apple.com/kb/PH5068?locale=en_US&viewlocale=en_US  
(FireFox opt-in feature):  
http://www.ghacks.net/2015/02/07/mozilla-starts-to-push-reader-mode-to-desktop-firefox/  
- text to speech:  
http://www.chromevox.com/  
http://www.apple.com/accessibility/osx/voiceover/  
- OS X text/speech system features (more then decade old):  
http://hints.macworld.com/article.php?story=20050503162056347

**Comment by jdaudier** [comment]
woah! lots of tools

**Pull request merged**
