### PR TITLE
Fix download page

### LINKED ISSUE #478: Download links broken
Reported by @flaviovs - the links on http://marionettejs.com/download/ to the .tar.gz and .zip files are empty.

### PR DESCRIPTION
**Pull request by denar90**
Bash script didn't want to copy files into dir with is not present.
Resolves #478

### CODE REVIEW

**Comment by scott-w** [comment]
👍

**Comment by rafde** [comment]
👍

**Comment by flaviovs** [comment]
:thumbsup:

Working now, thanks.

p.s.: both .tar.gz and .zip files contain a stray "tmp" directory in the archive. In other words, files uncompress to "tmp/backbone.marionette" by default. This also happened in 2.4.7 archives at least. The fix is trivial. Worth a new issue? Prefer a PR?

**Comment by paulfalgout** [comment]
PR welcomed. 🎊

**Comment by flaviovs** [comment]
No problem. Here it goes: #481

**Pull request merged**
