### PR TITLE
Add mobile nav

### PR DESCRIPTION
**Pull request by jdaudier**
Here's a vid: http://screencast.com/t/8F4yMysO6

nav

----
**ON CLICK** 

nav2

### CODE REVIEW

**Comment by sethkrasnianski** [comment]
This is awesome

**Comment by jdaudier** [comment]
@kkemple @samccone i added more space above & below the hamburger icon, rebased w/ master.  i think this is good to go.

**Comment by jasonLaster** [comment]
Love the burger. Would it be too meta to put the burger on strings Mn style?

**Comment by jdaudier** [comment]
@jasonLaster icon might get kinda small though

**Comment by samccone** [comment]
:clap:

**Pull request merged**
