### PR TITLE
add doc ordered files

### PR DESCRIPTION
**Pull request by denar90**
I've added files order for doc.
```
    'marionette.application.md',
    'marionette.approuter.md',
    'marionette.object.md',
    'marionette.abstractview.md',
    'marionette.view.md',
    'marionette.itemview.md',
    'marionette.collectionview.md',
    'marionette.compositeview.md',
    'marionette.layoutview.md',
    'marionette.region.md',
    'marionette.regionmanager.md'
```

This files will be shown first, then other doc files. 
Also I added some improvements for order functionality.
@scott-w can you verify this order? Is it fine?

### CODE REVIEW

**Comment by scott-w** [comment]
It looks alright for the current docs, though we're looking to put out docs for the new pre-release that changes a lot of the documentation. @ahumphreys87 Do we have a rough timescale for when this is happening?

**Comment by denar90** [comment]
I've been thinking to add some description into contribution guide for Mn repo. Something like:
"If you want to order some doc files, just add changes to `tasks/consts.js` in `marionettejs.com` repo"
So during next pre-release file `tasks/consts.js` can be easily changed.

**Comment by jdaudier** [comment]
> I've been thinking to add some description into contribution guide for Mn repo. Something like:
> "If you want to order some doc files, just add changes to tasks/consts.js in marionettejs.com repo"
> So during next pre-release file tasks/consts.js can be easily changed.

👍

**Comment by jdaudier** [comment]
Thanks @denar90!

**Pull request merged**
