### PR TITLE
Add critical css.

### PR DESCRIPTION
**Pull request by samccone**
Tested locally and works like a charm

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
I'd leave font loading in the header though - just to do things in small steps.
Not including fonts in header can results in flash of styles on web page. We use custom web font for critical content on above the fold

**Comment by samccone** [comment]
sure makes sense we do not have to merge #242 I can just close it for now

**Comment by jdaudier** [comment]
Someone help me understand what this does?  I'm assuming we're using [Critical](https://github.com/addyosmani/critical) and only the above the fold CSS is loaded first until user scrolls down?

**Comment by peterblazejewicz** [comment]
@jdaudier 
The headless browser loads a page using the widest dimensions assumed for our users (we have 1200px container width) and when page loads it outputs what styles are used to render content in visible fold (above the fold). We will use this output (via grunt task) to inject it into compiled html page header section - so that style is inlined and executes as page is loading. Our current style will be added to bottom of the page - so it will be loaded and parsed after the above the fold content is already rendered on screen. 
Usually that is very hard to achieve in complex, dynamic websites - but with static pages like here we could succeed.
We have now very good page speed index (yesterday it was < 1000 http://www.webpagetest.org/result/150214_RN_A3R/1/details/) and if we optimize above the fold - we will please users (and Google index per saldo)

**Comment by jdaudier** [comment]
@peterblazejewicz 

So above-the-fold CSS is injected inline and then after user scroll past the fold, the regular CSS is used (not inline)?  Did I get that right?

**Comment by peterblazejewicz** [comment]
@jdaudier it gets injected either manually by adding a link at the bottom of the page (as in this PR) or asynchronously injected by JavaScript executed as the bottom script (so not from header).
It has nothing common with our scroll UX pattern

**Comment by jdaudier** [comment]
@peterblazejewicz Not sure I get it.  I see a link to the CSS in the `<body>`.

**Comment by samccone** [comment]
hey @jdaudier take a look at this article 
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/

it does a really great job of explaining why this is a desirable PR.

**Comment by samccone** [comment]
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css

^^ this page in particular

**Comment by peterblazejewicz** [comment]
@samccone It worked nicely:
image
We got better in every aspect. I think I could again add reverted #236

**Comment by samccone** [comment]
kk lets revert it!

**Comment by peterblazejewicz** [comment]
just for records:

**Pull request merged**
