### PR TITLE
remove invalid tags for docs

### PR DESCRIPTION
**Pull request by denar90**
PR for issue #449

### CODE REVIEW

**Comment by jdaudier** [comment]
@denar90 Could you please fix the merge conflict?  Thanks!

**Comment by denar90** [comment]
fixed

**Comment by ahumphreys87** [comment]
do we not want to keep the docs for up coming pre releases? Maybe just ensure they are not the default selected version  - i.e. current should be latest stable version

**Comment by denar90** [comment]
Do we need pre releases in doc? Maybe cut them at all, if we have some really good doc in pre release we can include it (e.g. v3.0.0-pre.4). Because now all v3-pre with not finished doc and people are really confused.

**Comment by denar90** [comment]
@ahumphreys87 what whould you suggest, just set current version to v2.4.5 ?

**Comment by ahumphreys87** [comment]
Yeah I think that is best

**Comment by denar90** [comment]
@ahumphreys87 added fix. It really make sense to store all tags and only change current version.

**Comment by ahumphreys87** [comment]
💃 great work @denar90 

👍

**Comment by jdaudier** [comment]
Thanks for the help @denar90!

**Comment by samccone** [comment]
boom nice work @denar90

**Comment by denar90** [comment]
Thank you guys :)

**Pull request merged**
