### PR TITLE
Add semantic meaning to videos section content.

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This PR enhances textual content of web page in videos section that it can be finally read:
https://soundcloud.com/peter-blazejewicz/video-tags-text-to-speech-sample
```
Marionette Behaviors

Jason Laster explains how to use Marionette Behaviors. Slides: http://mbx.cm/t/9GBSw Sponsored by: http://www.infor.com
Marionette.js: http://marionettejs.com Dancing with Marionette Meetup: http://...

Marionette Behaviors

Backbone.Wreqr

James Smith explains how you can use Backbone.Wreqr. Slides: http://mbx.cm/t/TtNgU Sponsored by: http://www.infor.com Marionette.js:
http://marionettejs.com Dancing with Marionette Meetup: http://ww...

Backbone.Wreqr
```
or analyzed:
```
Item 
type:	http://schema.org/videoobject
property:	
name:	James Smith - Marionette The Backbone Framework
description:	
embedurl:	https://youtube.googleapis.com/v/EvQnntaqVdE
author:	James Smith
duration:	T28M44S
isfamilyfriendly:	true
thumbnail:	images/youtube/EvQnntaqVdE.jpg
url:	https://youtube.googleapis.com/watch?v=EvQnntaqVdE
alternativeheadline:	Marionette - Le framework Backbone
```
while keeping existing look and ux in place.

It's also a part that should be finished and in place before moving everything within page (again):
https://gitter.im/marionettejs/marionettejs.com?at=54e548c5ae387dd33003e972

This PR does not heavily effect the final size of html markup (I'll shave/trim down other parts to keep size smaller incrementally).
- add additional information to videos data json file
- rewrite videos section markup
- use Schema.org VideoObject meta tags to describe videos

The data and fields come from YouTube service JS API information at the time of this PR.

I'd be glad if someone can review this PR (though I've already tested it couple of times)
/cc @jdaudier could you install this PR and verify build?

Thanks!

### CODE REVIEW

**Comment by jdaudier** [comment]
@peterblazejewicz i ran this and was able to see all the videos

**Comment by peterblazejewicz** [comment]
PR post-mortem:
image

**Comment by samccone** [comment]
:D

**Comment by jdaudier** [comment]
@peterblazejewicz What's the purpose of adding Schema.org VideoObject meta tags? SEO?

**Comment by peterblazejewicz** [comment]
@jdaudier to:
- the page itself has a little better text - even if not visible (we have build a carousel but only with simple, short (as managed by width of video object) of what it the current *div* at all - like `Marionette 101` - which does not mean much I think, it's a topic or title known only to people already attended Mj meetup)
- we do not have a separate link to each video within our domain (yet) - the same for a book or screencasts - but we provide now a context (text, phrases) that can lead to other content - so we try to hint where to find a content - all through our web site.
For example - a book with Marionette as subject, people will not find our web site looking for a book - but we help them to find Leanpub resource - through our web site:
image
- even if we do not have an generic link for such described video or book on our web page - the people will find us (above description still applies - we first try to educate people, not to gain traffic). For example if you dig into Google images results looking for images with Mj in different context you will now find:
image
which has a data around it:
```
book
itemType = http://schema.org/Book
name = Structuring Backbone Code with RequireJS and Marionette Modules
description = Learn to use javascript AMD in your apps the easy way
url = https://leanpub.com/structuring-backbone-with-requirejs-and-marionette?utm_campaign=structuring-backbone-with-requirejs-and-marionette&utm_medium=embed&utm_source=marionettejs.com
image
href = images/books/requirejs.png
text = Structuring Backbone Code with RequireJS and Marionette Modules
```

So this PR just tries to enhance people experience - or a way they could reach us - either directly via link to a page - or by learning subjects covered by videos - and I hope we will help them to find these videos.

**Comment by jdaudier** [comment]
@peterblazejewicz thanks for the explanation! 🏄

**Comment by peterblazejewicz** [comment]
@jdaudier 
> the page itself has a little better text - even if not visible (we have build a carousel but only with simple, short (as managed by width of video object) of what it the current div at all - like Marionette 101 - which does not mean much I think, it's a topic or title known only to people already attended Mj meetup)

You can already find results of adding this - exactly in expected way as helpful hints for users. If you search for `marionette 101` you will find - among other things - a reference to our page with `description` we have just added - even if there is no direct link:

**Comment by jdaudier** [comment]
nice!  that puppet making 101 video is scary ☻

**Comment by peterblazejewicz** [comment]
@jdaudier now on video, Mj and Etsy:

As one can see from screenshot - we don't have such text on web page visible - it's within data added via this PR - so we help someone to find information she could be looking for

**Comment by jdaudier** [comment]
gotcha... what tool do you use to see this?
image

**Comment by peterblazejewicz** [comment]
@jdaudier That's Google's rich snippet validator:
https://developers.google.com/structured-data/testing-tool/?url=http%253A%252F%252Fmarionettejs.com%252F
Warnings are `OK` but we should take some action or at least verify what's on. The `errors` are not OK (but there is none).

**Comment by jdaudier** [comment]
thanks!

**Comment by samccone** [comment]
yeah TIL

**Pull request merged**
