### PR TITLE
Add Button UI component into source code

### PR DESCRIPTION
**Pull request by peterblazejewicz**
Based on recent discussion in this issue #267 and requirement to move forward with optimizing source and output code, here is a first of such (hope) improvements that brings extracted from current version abstracted *button* like UI component that can be applied to any tag (expected use on a, button, input tags) together with two concrete versions (`primary`/`secondary`) of two existing patterns used on our web site.
- add components directory
- add reusable base `button` class
- add two base subclasses based on current design
- make sure we are using common UX pattern in component implementation
- add reusable mixin to quickly generate other subclasses

So there is one *abstract* class that has no background, border or color exact definition and can be extended in subclasses here.
The naming does not use BEM and uses standard objectified-naming solutions.
The dimensions of components are based on existing ones - though they are differently computed to allow efficient adaptation to scaled font sizes (we use paddings + border - as e..g in Bootstrap).

You can view live version on JSBin here:
http://jsbin.com/maziso/19/edit?css,output
(sass + html live output exactly as used in PR and on our web site using envisioned class names).

The change brings new class names to avoid collision with existing 'btn' (which is nicer and shorter). When introduced and refactored in existing code - the `btn` can be reintroduced instead of `btn` if someone wants (Bootstrap uses `btn`, Foundation `button`, etc).

/cc @jdaudier

### CODE REVIEW

**Comment by samccone** [comment]
yay I like this

**Comment by samccone** [comment]
@jdaudier just waiting on your :eyes:

**Comment by jdaudier** [comment]
@peterblazejewicz A few questions...

1. Would any of the following go under the "components" scss folder too?
back-to-top-button.scss
animation
bass
ui
variables

2. Should we move some of the button styling under `ui.scss` to `buttons.scss`?

**Comment by peterblazejewicz** [comment]
@jdaudier 
we could pick a solution + guide and stick to it. For example this one is frequently used:
http://sass-guidelin.es/

So `back-to-top` yes, can be reworked into *componen* and go to buttons.

> Should we move some of the button styling under ui.scss to buttons.scss?

No, these are `drop-ins` - i can switch classes to anchor tag and then adapt layout by adding correct container for these buttons (I want to get `btn` class when things are fixed). The current classes for buttons have declarations for where and how display these components - which causes problem with duplicated, undetermined selectors.
so instead of this:
```html
a.btn.btn-action.secondary-color(href = "/docs/current") View Docs
```
I can now refactor:
```html
a.button.secondary-action(href = "/docs/current") View Docs
```
and just add wrapping elements to maintain *where and how* display contained button(s)

I want that we refactor current code slightly - so we have less problems now and in the future.

**Comment by jdaudier** [comment]
@peterblazejewicz Mind moving the `back-top-top` under components then for this PR?

And if I understand you correctly, you're saying that we'll eventually phase out the styling for buttons under the ui.scss, correct?

**Comment by peterblazejewicz** [comment]
@jdaudier yes, we could move things into more *established* places - so anyone will know where the component is located (or where to find it). These patterns are well established, see:
https://github.com/google/web-starter-kit/blob/master/app/styles/components/_components/_button.scss
https://github.com/zurb/foundation/blob/master/scss/foundation/components/_buttons.scss
https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_buttons.scss
We simply can't spray positioning code to buttons on partial sass files anymore - as there is no single page anymore. So we have to put *extracted* styles into some logical places and do other things, that start to break too.

**Comment by jdaudier** [comment]
sounds good @peterblazejewicz

**Comment by jdaudier** [comment]
LGTM :+1:

**Comment by peterblazejewicz** [comment]
Thanks! merging

**Pull request merged**
