### PR TITLE
Add 3 example apps

### PR DESCRIPTION
**Pull request by jdaudier**
@peterblazejewicz There's prob a more graceful way of doing the responsiveness [here](https://github.com/marionettejs/marionettejs.com/pull/391/files#diff-b229b868918a6159b7876b3551f06032R16). Thoughts?

cc/ @samccone @jmeas @thejameskyle - hope it's ok to feature your app

### Desktop
image

### Tablet
image

### Mobile
image

### CODE REVIEW

**Comment by jdaudier** [comment]
@peterblazejewicz how do I get Travis to pass? I have the latest code pulled down.

**Comment by peterblazejewicz** [comment]
@jdaudier that is outstanding issue with Travis CI script:
https://github.com/marionettejs/marionettejs.com/issues/375
I've been trying to find out the reason of this error, but yet haven't succeeded.

**Comment by peterblazejewicz** [comment]
> @peterblazejewicz There's prob a more graceful way of doing the responsiveness here. Thoughts?

@jdaudier there is already `.btn-wrapper` in place in your code. It should be used:
- to position/offset content using `margin-top` (currently margin is added to button itself)
Buttons can be simply always display as block, container can be scaled, but not UI elements:
https://github.com/twbs/bootstrap/issues/13647.
So you could do not apply a *block* style to all buttons, but only apply it under certain breakpoint. That's up to you.

**Comment by peterblazejewicz** [comment]
As these are real, existing web objects/applications, I'd add semantic tags to them later, after PR is merged.
:+1:

**Comment by jdaudier** [comment]
@peterblazejewicz I'll leave you to the `semantic tags` since I'm not exactly sure what you are talking about specifically.

I'll see if I can position the button differently so that I don't have to give a height to the parent container.  I wanted all of them to be docked to the bottom & lined up.... which sounded easy but... :facepunch:

**Comment by jdaudier** [comment]
@peterblazejewicz refactored the scss to be cleaner

I decided to not line up the buttons and just have it flow naturally

**Desktop**
image
====
**Tablet**
image
====
**Mobile**
image

**Comment by peterblazejewicz** [comment]
@jdaudier here is another link against applying layouts directly to UI elements:
https://github.com/yahoo/pure/issues/469#issue-63848357
https://github.com/yahoo/pure/issues/469#issuecomment-85238662

**Comment by jdaudier** [comment]
@peterblazejewicz so you're suggesting removing the margin-top from the btn itself and add it to the btn-wrapper instead?

**Comment by peterblazejewicz** [comment]
@jdaudier maybe not yet, but as consideration. Spacing UI elements should be careful. I'd rather use container and space it per design. Bootstrap does not space buttons, except of specific use-case: http://git.io/veWEc while Foundation adds bottom margin to all buttons: http://git.io/veWER

**Comment by jdaudier** [comment]
Ok... looks good to merge?

**Pull request merged**
