### PR TITLE
Add logo animation on mouse enter

### LINKED ISSUE #54: Marionette logo needs to be animated...
leaving this one wide open.......

### PR DESCRIPTION
**Pull request by jdaudier**
On mouse enter...

**Video of the animation:**
http://screencast.com/t/XKIns9rbZ6

**Animated gif (not as smooth as the video but you get the idea):**
q6ijyacgjq

### CODE REVIEW

**Comment by samccone** [comment]
Can we use a version of snabbit from bower?

**Comment by jdaudier** [comment]
you got it @samccone  :arrow_up:

**Comment by samccone** [comment]
One commit and we can ship

**Comment by jdaudier** [comment]
ok, it's now 1 commit

**Pull request merged**
