### PR TITLE
Update inspector section

### PR DESCRIPTION
**Pull request by jdaudier**
ok iteration 2

### CODE REVIEW

**Comment by samccone** [comment]
make sure to delete the old logo

**Comment by samccone** [comment]
:+1: from me once you delete the image @jdaudier 

@peterblazejewicz let me know what you think

**Comment by jdaudier** [comment]
ok - old inspector logo deleted @samccone

**Comment by samccone** [comment]
Looks like you need to rebase

**Comment by jdaudier** [comment]
@samccone ok done rebasing

**Comment by samccone** [comment]
kk we can put this in once @peterblazejewicz gives it the once over 

thanks @jdaudier

**Comment by jasonLaster** [comment]
Ooh I love it. :heart_decoration: 

It makes me really proud to see the inspector laid out do well. 

btw I think the copy could be better. Stop being humble joanne and sell it :) I know you can.

**Comment by jmeas** [comment]
I think the copy needs an article (like 'the' or 'a') at the start.

> World-class inspector

vs.

> A world-class inspector

**Comment by jdaudier** [comment]
k @jmeas added that

img

**Comment by peterblazejewicz** [comment]
LGTM
:+1: 
I would probably 
- [ ] record this animated GIF with LICECap (which I'm using here) - so clicks are recorded with user interaction flow: https://github.com/lepht/licecap
- [ ] record via screen capture to video - use placeholder image with the same UI as in videos section.

The animated GIFs is enough for us here  I think - but on Inspector own, dedicated page I'd use recorded screencast video (can be muted, but with cool, free sound background). GIF should be short to save size.

**Comment by jdaudier** [comment]
@peterblazejewicz yup, agreed... screen recording would be great for Inspector's own page (ping @jasonLaster)

For now, I updated the gif to include the hand cursor icon to draw attention to where the user was clicking in the screenshots.

img

**Comment by samccone** [comment]
yeah @jdaudier nice, I think this is a good first step. We can iterate on the animation.

thanks for the looking and review @peterblazejewicz

**Pull request merged**
