### PR TITLE
Add video about Browserify use with Marionette

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This PR adds data with very interesting video discussing Browserify use with Mj applications - I've found it really intereseting and I think it should be here to show this particular content on the web site and cross-link it via micro-tags.

- update data file
- add progressive version of video poster image

@jdaudier You've curated latest video order - mind do this with this one? Should it go by date or in specific order?

Thanks!

### CODE REVIEW

**Comment by jdaudier** [comment]
I think we should go in the order of a beginner learning... in the order we think one should learn marionette.

**Comment by jdaudier** [comment]
@kkemple :+1:

**Comment by peterblazejewicz** [comment]
@jdaudier So after or before `Inspector` (assuming `Inspector` is int/adv):
https://github.com/marionettejs/marionettejs.com/blob/master/src/data/videos.json#L47

**Comment by jdaudier** [comment]
How about after?

**Comment by peterblazejewicz** [comment]
@jdaudier done/rebased :)

**Comment by jasonLaster** [comment]
@kkemple we'll be promoting your talk!

**Comment by jdaudier** [comment]
Thanks peter!

**Comment by kkemple** [comment]
:+1: awesome! I have been traveling for days or I would have jumped in sooner :)

**Comment by peterblazejewicz** [comment]
@jasonLaster @kkemple 
https://www.google.pl/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=marionette%20browserify%20apps&es_th=1

`marionette browserify apps`

https://www.google.pl/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=browserify%20marionette%20app&es_th=1

`browserify marionette app`

that is - with *video boject* micro tags we are now able to get the content to the people even if there is no youtube video in the results:




Obviously YouTube has the #spot on video section:
image

**Comment by jdaudier** [comment]
@peterblazejewicz :+1:

**Pull request merged**
