### PR TITLE
Add Marionette Inspector section

### LINKED ISSUE #178: Add a link to the inspector high on the page
Right now, the only link is below Jason's talk, way down. I'm not sure where exactly the link should go, but I think it's important enough to be up high (maybe it should have its own section?)

### PR DESCRIPTION
**Pull request by jasonLaster**
fixes #178

Here's my brilliant copy:
```
 World class inspector for exploring your application's views, models, events and more. You won't know how you got by without it.
```

Open to suggestions on all of this, but also happy to push and refine. You know, nobody would really care if we iterate on this kind of thing

### CODE REVIEW

**Comment by samccone** [comment]
word not opposed at all to this!

looks like you are a bit behind @jasonLaster

**Comment by samccone** [comment]
@jasonLaster it looks like @meomix actually has a way to install streamus right on the page
https://streamus.com/

we should do this!

**Comment by MeoMix** [comment]
:) It's pretty simple to do, too.

You just have to mark your extension as supporting 'inline install' from the developer's extension page: http://i.imgur.com/CF5r584.png

and then run a bit of code: https://github.com/MeoMix/StreamusWebsite/blob/master/src/js/view/installButtonView.js#L44

**Comment by jasonLaster** [comment]
neat @MeoMix. I'll setup the permissions now so that anyone can grab this

**Comment by samccone** [comment]
:boom:

**Comment by jmeas** [comment]
Nice logo

**Comment by jasonLaster** [comment]
yup - @nerdpruitt killed it

**Comment by jasonLaster** [comment]
@samccone no longer behind

**Comment by peterblazejewicz** [comment]
Yes, inline style can be later refined via section class (out of Jade to scss)
As a user I usually like more the real `mockups` of tools as screenshots - so more like from Chrome web store - it speaks more to users what a tool is for - just my opinion.

**Comment by samccone** [comment]
@peterblazejewicz do you any opposition to merging this in and iterating on it more?

**Comment by peterblazejewicz** [comment]
@samccone no - it can go as is

**Comment by jdaudier** [comment]
My suggestion for next iteration... thoughts?

new

**Pull request merged**
