### PR TITLE
Update dependency version that broke build

### PR DESCRIPTION
**Pull request by jdaudier**
@trezy I had to change this back since it broke my build.

### CODE REVIEW

**Comment by trezy** [comment]
Coolies. As long as the build passes (I restarted it) :+1:

**Comment by jdaudier** [comment]
@trezy: build failed... Why?

**Comment by trezy** [comment]
Just looking at the log in Travis, I have no idea. I can take a look later if nobody else has figured it out.

**Comment by peterblazejewicz** [comment]
I think Sam can have some insight on this:
https://github.com/marionettejs/marionettejs.com/issues/375
That is wrapper code around non-standard exit code on Linux I think

**Comment by jdaudier** [comment]
@samccone any idea? Should I merge even if build fails?

**Comment by samccone** [comment]
yep I will take a look here :)

**Comment by jdaudier** [comment]
Any luck @samccone? Tks!

**Comment by samccone** [comment]
@jdaudier @peterblazejewicz @trezy do any of you have a version that works locally?

if possible can you run npm shrinkwrap and put that file in a gist for me?

**Comment by peterblazejewicz** [comment]
@samccone 
Done: https://gist.github.com/peterblazejewicz/370fdf1a49301366cd27
I had to make a small change in package.json though: #433

**Comment by jdaudier** [comment]
@samccone Here's mine: https://gist.github.com/jdaudier/10be428f37e12a8788b5

**Comment by samccone** [comment]
landing this

**Pull request merged**
