### PR TITLE
Add/inspector tags

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This PR consists of two commits;
- The first is a cleanup commit required to be done before adding tags to Inspector
page.
The removed property is not picked by machines for some reasons,
probably due to use of svg. That is something to be investigated in future.
The commit remove this (and related) property to not use them on Inspector page - which, as application - has no primary image of page meta.

- The second commit is a proper commit introducing rich meta tags used already on Mj landing page. We will expose following information from content already existing within page:
```
webapplication
itemType = http://schema.org/WebApplication
name = Marionette Inspector
description = A world-class inspector for exploring your application's views, models, events and more.
operatingsystem = Chrome
applicationcategory = Developer Tools
downloadurl
href = http://chrome.google.com/webstore/detail/marionette-inspector/fbgfjlockdhidoaempmjcddibjklhpka
text = Available in the Chrome Web Store
image
href = /images/inspector/inspector-preview.png
text = Marionette Inspector tab active in the Google Chrome browser examining a TodoMVC application
url
href = https://github.com/marionettejs/marionette.inspector
text = Fork me on GitHub!
```

Thanks!

### CODE REVIEW

**Comment by samccone** [comment]
ah sorry @peterblazejewicz mind getting a rebase on this?

**Comment by peterblazejewicz** [comment]
Do you mean updating from master (it's already done) or squashing into single one?

**Comment by peterblazejewicz** [comment]
Oh, I see github notice. OK

**Comment by peterblazejewicz** [comment]
Update/fixed/rebased
Thanks!

**Pull request merged**
