### PR TITLE
ci fixes WIP

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by jmeas** [comment]
lol

**Comment by jmeas** [comment]
i have so many PRs like this on projects i work on

**Comment by samccone** [comment]
:cactus:

**Comment by jasonLaster** [comment]
:stuck_out_tongue: :stuck_out_tongue_closed_eyes: :stuck_out_tongue_winking_eye:

**Comment by jasonLaster** [comment]
especially good bc travis

**Pull request closed without merging**
