### PR TITLE
Rewrite download section(s) markup and styles

### LINKED ISSUE #298: Invalid navigation links <520px
There is no content <520px (sm breakpoint) while there is a navigation link:
http://marionettejs.com/#download
We can't do such things - that is we cannot hide named section and left navigation link - the link is correct .
WIP

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- improve markup - shave and trim elements - use small inside of headers for
example - which is more natural and better controller in reponsive pages
- download section is now linked in 2 distinct ways. It cannot be just hidden as
users are able to use links on any device - so the content should be visible.
Remove .hidden-xs which was OK without direct links - now it's invalid UX
- remove div.section-header - just apply .section-header directly to headers (!)
- add sectioning of content using different levels of headers h2 > h3 (> h4)
- add small copy line to download section
- add "Install ..." to describe what *with* is for
- add semantics to Bower, Npm
- remove microformats properties non-applicable yet to download page
- add util header classes to correct styling while applying correct content
sectioning (for example we use h4 headers that should look exactly the same way
as h3 headers)
- fix h2 and h3 headers font size
- DO NOT USE ID selectors in style sheets #downloads was added as target for href - that is as navigation element - add section style class to use instead
of specific id

This PR also partially fixes #298 

@jdaudier mind reviewing?

### CODE REVIEW

**Comment by jasonLaster** [comment]
thanks @peterblazejewicz

**Comment by peterblazejewicz** [comment]
@jdaudier I'm gonna to merge this, can you review when have time?

**Comment by jdaudier** [comment]
@peterblazejewicz 2 quick things...

1. Do you mind if we update the text from
*OLD*: Get Marionette just the way you want it. We officially distribute via npm, bower, and static builds via our site.
*NEW OPTION 1*: Get Marionette just the way you want it. We officially distribute via npm, bower, and static builds on this site.
*NEW OPTION 2*: Get Marionette just the way you want it. We officially distribute via npm, bower, and static builds here.

2. Since you have that branch, could you move the whole header text block down a tad?  I feel like it should line up with the red part of the logo. It's something I've been meaning to tweak.

**Comment by peterblazejewicz** [comment]
@jdaudier done, rebase and squashed

**Comment by jdaudier** [comment]
@peterblazejewicz could you move the header text block down to match the logo part?  Like that whole text block and the header. Thx!

**Comment by peterblazejewicz** [comment]
@jdaudier updated, let's tweak it after PR, it looks different above breakpoint and below breakpoint:

**Comment by jdaudier** [comment]
sounds good! LGTM :+1:

**Pull request merged**
