### PR TITLE
Optimize page above the fold rendering. Closes #234

### LINKED ISSUE #234: Inline SVG logo/text in above the fold section #perfmatters
Let's try to improve page speed rendering by minimizing number of request of above the fold content:
- [x] inline brand image svg via data:image conversion
- [x] inline brand text svg via data:image conversion

This is supposed to optimize rendering speed by minimizing number of requests required to render ATF content (as per Google screenshot):

### PR DESCRIPTION
**Pull request by peterblazejewicz**
These commits will try to increase landing page Google ranking by optimizing above the fold rendering - which is counted in favour of web page on relation to mobile devices. See #234 issue for screen shot:
- load brand logo and brand text as inlined content via data:image
- move brand logo and text images to separate partials to keep development code clean

The svgs were converted to data:image base64 encoded strings using CSS Tricks technique:
```bash
echo -n `cat marionette-text.svg` | base64 | pbcopy
```
If envisioned aim of these commits is not achieved the commits will be reverted.

Thanks!

### CODE REVIEW

**Comment by samccone** [comment]
Yesssssssssss

**Comment by jmeas** [comment]
Was this a WIP @peterblazejewicz ?

**Comment by samccone** [comment]
This is a step in the right direction.  We still need to inline the css but this does remove some of the blocking content

**Comment by jmeas** [comment]
There's no build system in place to update these images if we wish to later on, though. He also left the old files in the repo.

I mean, idk, the state of the commit + the msg suggested to me that this is a WIP. @peterblazejewicz can speak for himself tho'

**Comment by peterblazejewicz** [comment]
@jmeas Yes, I've left old SVGs on purpose. It appears that inlining only SVGs does not helped much - and on the contrary we've got worse indicator here:
```
Only about 45% of the final above-the-fold content could be rendered with the full HTML response see screenshot.
```
I"ll revert this commit/PR
Thanks!

**Comment by peterblazejewicz** [comment]
reverted: https://github.com/marionettejs/marionettejs.com/pull/236

**Comment by peterblazejewicz** [comment]
The web site got page speed index < 1000 (which is desired and very good index):
http://www.webpagetest.org/result/150214_RN_A3R/1/details/
So at the current state of the page I think we should not bother with page speed, just keep in mind above the fold rendering on mobiles that needs improvements.
Small improvements are always plausible and should be welcomed.

**Pull request merged**
