### PR TITLE
Swap to white shirt image

### PR DESCRIPTION
**Pull request by jdaudier**
since that's what they actually sell

### CODE REVIEW

**Comment by samccone** [comment]
@jdaudier can you compress this image :)

**Comment by jdaudier** [comment]
k... one sec

**Comment by samccone** [comment]
I use http://pngmini.com/

**Comment by jdaudier** [comment]
oh i just used photoshop... is 35KB small enough? or should i try pngmini?

**Comment by thejameskyle** [comment]
No for the reasons I outlined in chat. Opening PR to remove shirts shortly.

**Pull request closed without merging**
