### PR TITLE
improve mobile site

### PR DESCRIPTION
**Pull request by samccone**
**Before**

**After**

I also hid the requirements, screencasts, and inspector install button on mobile, since they are all pretty useless actions on mobile

### CODE REVIEW

**Comment by paulfalgout** [comment]
:+1: on everything except maybe the inspector install.

Obviously you're not going to install it on mobile, but from the chrome store on mobile you can install the extension to your desktop.. so I don't know if it's useless.

**Comment by samccone** [comment]
oh interesting @paulfalgout 

based on the heatmap.. no one has clicked it

**Comment by samccone** [comment]
but I agree @paulfalgout I will drop that commit

**Comment by jdaudier** [comment]
:+1:

**Comment by peterblazejewicz** [comment]
@samccone you will need to update, rebase and apply correction to incorporate current html structure (we are using tags - instead of classes :( ) on header section from this PR:
https://github.com/marionettejs/marionettejs.com/pull/244
Something like (after updates):
```diff
diff --git a/src/stylesheets/_header.scss b/src/stylesheets/_header.scss
index ee94cc6..80c4ad0 100644
--- a/src/stylesheets/_header.scss
+++ b/src/stylesheets/_header.scss
@@ -20,11 +20,16 @@
     margin: auto;
     padding: 60px;
     max-width: 1200px;
+    overflow: hidden;
 
     .secondary-color {
       min-width: 154px;
     }
 
+    @include below($med-breakpoint) {
+      padding: 10px 0 0 0;
+    }
+
     .left {
       width: 30%;
 
@@ -40,12 +45,6 @@
         right: 20px;
       }
 
-      @include below($med-breakpoint) {
-        width: 100%;
-        padding: 0;
-        text-align: center;
-      }
-
       h1, p {
         text-align: left;
         color: $dark-gray;
@@ -61,6 +60,20 @@
         margin-bottom: 15px;
         font-size: $large-font;
       }
+
+      @include below($med-breakpoint) {
+        width: 100%;
+        padding: 0;
+        text-align: center;
+
+        h1, p {
+          text-align: center;
+        }
+
+        h1 {
+          margin-top: 30px;
+        }
+      }
     }
   }
 }
@@ -121,15 +134,15 @@
 
     .nav-slider {
       float: right;
-      
+
       &__list {
-        float: left;  
+        float: left;
         > li {
           position: relative;
           display: block;
-        }  
+        }
       }
-      
+
       @include below(660px) {
         background-color: $red;
         float: none;
@@ -142,7 +155,7 @@
         transition-duration: .5s;
         transition-timing-function: cubic-bezier(0, 1, 0.5, 1);
         -webkit-transition-timing-function: cubic-bezier(0, 1, 0.5, 1);
-        
+
         &__list {
           float: none;
         }
@@ -158,7 +171,7 @@
         display: inline-block;
         padding: 0 14px;
         cursor: default;
-        
+
         @include below(660px) {
           display: none;
         }
```

**Comment by samccone** [comment]
boom looks so much better now

screen shot 2015-02-15 at 3 04 27 pm

**Pull request merged**
