### PR TITLE
Refactor/inspector

### PR DESCRIPTION
**Pull request by peterblazejewicz**
/cc @jdaudier 

This PR:

- move `inspector/index.scss` into top level folder and make it a main file in terms of Sass guidelines. We now use this file as `inspector.scss` - that is a main file for `inspector` part of web site (we use separate file to minimize payload size - so we don't share marionette.css and use dedicated file)
http://sass-guidelin.es/#main-file
We will have now a clean distinction of main Sass files on top level:
```
api.scss
docs.scss
inspector.scss
marionette.scss
```
- correct invalid favicon - it simply didn't rendered at all on inspector web page. After this change most of browser will just pick `favicon.ico` file from root directory as per default implementation

- move block related to favicons into the same location as in main `layout.jade` - so in future we could create a top level layout file if required with less efforts I hope

- fix bottom navigation and make links to work like a buttons:

footer

- shave some bits from inspector preview png image (as pointed in Google Speed insights)

Tested with critical for regressions.

Thanks!

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/marionettejs/marionettejs.com/pull/334" target="_blank">ReviewNinja

**Comment by jdaudier** [comment]
sorry guys... i'll figure out out how to remove review ninja...:smile:

**Comment by peterblazejewicz** [comment]
NP :smile:

**Comment by jdaudier** [comment]
ok removed... although the icon is quite cute

**Comment by peterblazejewicz** [comment]
http://mean.io/system/assets/img/ninja/banner-top-ninja.png

**Pull request merged**
